### ISSUE TITLE
Flow wouldn't open after installing

### ISSUE THREAD

**Issue by DBradleyRI** [Exarilo/Flow.Launcher.Plugin.AppUpgrader#1]
I have the latest Flow Launcher installed (1.19.1) on a Windows 11 device. Installed the plugin and Flow wouldn't open at all until I deleted the folder. Tried reinstalling and it happened again.

**Comment by Exarilo** [comment]
thanks for the report. 
It's strange it works well for me with the same setup.
I'm going to see that next week. 
it may be a language problem winget does not have the same labels depending on the language
