### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by ak1dd** [Exarilo/Flow.Launcher.Plugin.AppUpgrader#2]
I use winget daily...   After watching the video here, I installed the plugin, FlowLauncher restarts, type 'up'...  nothing happens.  No error message, nothing.   I confirmed the plugin is installed 

AppUpgrader 1.0.3

Using Windows 11 Version 10.0.26100 Build 26100
Winget v1.8.1911
Flow Launcher 1.19.3

**Comment by Exarilo** [comment]
Hi,
Thank you for your feedback. I've tested the plugin on my machine, and it works fine for me. I'm not sure if this will resolve your problem, but I've made an update that should be released in Flow Launcher in a few hours. I hope this resolves the issue

**Comment by ak1dd** [comment]
upgraded to 1.0.6 ... no difference.   Uninstalled it.  Reinstalled it.   Nothing.

When writing this it occurred to me, "What happens if there are no available updates?"    Winget lists nothing is available to update when I run it right now.  Is AppUpgrader correctly detecting there are no updates but there is no communication of that to the user?  If this is the case, could you display something like "Nothing to update..." as a search result?  Anyway, cool plugin.   Thanks.

**Comment by ak1dd** [comment]
I had updates available via winget this morning and tried AppUpgrader.  It didn't work.  I uninstalled and reinstalled and it didn't work.   I enabled and disabled the plugin, didn't work.   On a whim, I completely shut down flow launcher and relaunched it.   It worked.  I don't have time to do more testing but this is the first time I've seen it working.   Perhaps this is the issue?

**Comment by Exarilo** [comment]
I will look into it. I am currently experiencing the same problem (sometimes it works, sometimes it doesn’t). The issue might be related to the initialization order, as both Flow Launcher and winget start at boot, potentially causing a priority conflict.

I have been focusing more on my other plugin, LinkOpener, recently, but I now have time to address this and will work on fixing it to ensure the plugin works smoothly.

**Comment by ak1dd** [comment]
Thanks.   It isn't working again.  But when it did work it was super fast and really cool.    If it is possible and it doesn't do this already, I'd really suggest a message like winget gives if you run "winget update" and there are no updates.   "No installed package found matching input criteria."   Or maybe more friendly "No updates found..."

**Comment by Exarilo** [comment]
I've made some improvements to enhance performance further. The plugin should display consistently now, even if there are no updates available, with a message to keep you informed.

**Comment by ak1dd** [comment]
Very cool! I had it disabled until today.  It now seems to work.  Thanks for your work.  I am really surprised this isn't a very popular plugin.

**Comment by Exarilo** [comment]
Thanks for your message! I’m happy to hear it’s working now. I guess the plugin isn’t very popular because it wasn’t working well for a while 😉
