### ISSUE TITLE
[SUGGESTION] Filter by query

### ISSUE THREAD

**Issue by cibere** [Exarilo/Flow.Launcher.Plugin.AppUpgrader#4]
Hello! I noticed that the program seems to give a static list, which I have to search through. This could be a very long list, so getting the specific app I want could take a little bit.

Would it be possible to filter by query? Do if I did `up apple` for example, it would show `apple application support` at the top instead of in the middle.
Example of current behavior showing apple in the middle:
![image of current behavior](https://github.com/user-attachments/assets/93977ca4-7128-4ab5-8749-0dc7c9248a1a)

**Comment by Exarilo** [comment]
Hi !
Thanks for the suggestion that's a great idea! 
I've just committed the change, it will be available soon
