### ISSUE TITLE
[SUGGESTION] App Icons

### ISSUE THREAD

**Issue by cibere** [Exarilo/Flow.Launcher.Plugin.AppUpgrader#5]
Hello again, I have another suggestion.

The icon used for all apps is the default AppUpdater icon, would it be possible to use the app's icons instead? It would help find the app you are wanting to update faster

**Comment by Exarilo** [comment]
I agree, using the app's icons would be cool. Unfortunately, I don't have direct access to the icons through Winget, but I'll take a closer look to see if there's a workaround.
